# Generated by Django 3.0.7 on 2020-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='активный')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
            },
        ),
    ]
