# Generated by Django 3.0.7 on 2020-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position'], 'verbose_name': 'баннер', 'verbose_name_plural': 'баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='ссылка'),
        ),
    ]
