# Generated by Django 3.0.7 on 2020-10-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20201021_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
    ]
