# Generated by Django 3.0.7 on 2021-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20201022_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(help_text='часть ссылки', unique=True, verbose_name='слаг'),
        ),
    ]
