# Generated by Django 3.0.7 on 2020-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20201009_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
