# Generated by Django 3.0.7 on 2020-10-10 05:48

from django.db import migrations


def calculate_price_to_order_items(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all():
        order_item.price = order_item.product.price * order_item.quantity
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_price_to_order_items),
    ]
