# Generated by Django 3.0.7 on 2020-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Отменен'), ('1', 'Необработанный'), ('2', 'Выполняется'), ('3', 'В пути'), ('4', 'Доставлен')], default='1', max_length=2, verbose_name='статус'),
        ),
    ]
