# Generated by Django 3.0.7 on 2020-10-11 15:27

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20201011_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='дозвон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='доставлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 15, 25, 24, 490765, tzinfo=utc), verbose_name='поступил'),
        ),
    ]
