# Generated by Django 3.0.7 on 2020-10-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20201011_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('0', 'Наличными курьеру'), ('1', 'Интернет-оплата'), ('2', 'Картой курьеру')], default='0', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
