# Generated by Django 3.0.7 on 2021-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Наличными курьеру'), (1, 'Интернет-оплата'), (2, 'Картой курьеру')], default=0, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отменен'), (1, 'Необработанный'), (2, 'Выполняется'), (3, 'В пути'), (4, 'Доставлен')], default=1, verbose_name='статус'),
        ),
    ]
