# Generated by Django 3.0.7 on 2021-03-25 03:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210325_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='79998887766', max_length=128, region=None, verbose_name='мобильный номер'),
            preserve_default=False,
        ),
    ]
