# Generated by Django 3.0.7 on 2021-03-25 03:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_new_format_for_phonenumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_phonenumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='мобильный номер'),
        ),
    ]
