# Generated by Django 3.0.7 on 2021-07-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20210325_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Наличными курьеру'), (1, 'Интернет-оплата'), (2, 'Картой курьеру')], db_index=True, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodcartapp.Product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
